# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: DevRel Nightly Pipeline
on:
  push:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *'
env: 
  APIGEE_USER: ${{ secrets.APIGEE_USER }}
  APIGEE_PASS: ${{ secrets.APIGEE_PASS }}
  APIGEE_ORG: ${{ secrets.APIGEE_ORG }}
  APIGEE_ENV: ${{ secrets.APIGEE_ENV }}
jobs:
  get-steps:
    name: Get DevRel Steps
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2

    - id: set-matrix
      run: echo "::set-output name=matrix::$(cat steps.json)"

  quality-check:
    name: DevRel Workflow Checks
    runs-on: ubuntu-latest
    needs: get-steps                                         
    strategy:                                                
      matrix: ${{needs.get-steps.outputs.matrix}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: run check
        uses: ./tools/pipeline-runner
        with:
          pipeline-action: ${{ matrix.steps }}

